server {
    listen 8080;
    server_name _;
    root /var/www/devops-hackathon-006-nguyenquanghuy/devops-hackathon-006-nguyenquanghuy/src/var/www/devops-hack>
    index index.html;

    access_log /var/log/nginx/devops-hackathon-006-nguyenquanghuy.access.log;
    error_log  /var/log/nginx/devops-hackathon-006-nguyenquanghuy.error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}


